apiVersion: apps/v1
kind: Deployment
metadata:
  name: jadn-sandbox
  namespace: jadn-sandbox
  labels:
    app: jadn-sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jadn-sandbox
  template:
    metadata:
      labels:
        app: jadn-sandbox
    spec:
      containers:
        - name: jadn-sandbox
          image: "screambunn/jadn_sandbox:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: jadn-sandbox-config
                  key: API_BASE_URL
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: jadn-sandbox-config
                  key: ENVIRONMENT
