apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jadn-sandbox
  namespace: jadn-sandbox
  labels:
    app: jadn-sandbox
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: jadn-sandbox.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jadn-sandbox
                port:
                  number: 80
