apiVersion: v1
kind: Service
metadata:
  name: jadn-sandbox
  namespace: jadn-sandbox
  labels:
    app: jadn-sandbox
spec:
  type: ClusterIP
  selector:
    app: jadn-sandbox
  ports:
    - port: 80
      targetPort: 8082
      protocol: TCP
      name: http
